name: Simple Project

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        
    - name: Test
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
